default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password:

development:
  <<: *default
  database: sample-app_4_0_dev
  host: localhost

test:
  <<: *default
  database: sample-app_4_0_test
  host: localhost

production:
  <<: *default
  host:     <%= ENV['PROD_DATABASE_HOST'] %>
  database: <%= ENV['PROD_DATABASE_NAME'] %>
  username: <%= ENV['PROD_DATABASE_USERNAME'] %>
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>
